### ISSUE TITLE
fix mypy pre-commit issues

### ISSUE THREAD

**Issue by worldworm** [worldworm/copier-poetry-meta#7]
tried the following pre-commit configuration:
```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--config-file=backend/pyproject.toml]
        language: python
        types: [python]
        additional_dependencies: [pydantic-settings]
        exclude: tests(/\w*)*
```
got the following errors:
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

test/database.py:6: error: Module "alembic" has no attribute "command"  [attr-defined]
test/database.py:23: error: Unused "type: ignore" comment  [unused-ignore]
alembic/env.py:9: error: Module "alembic" has no attribute "context"  [attr-defined]
Found 3 errors in 2 files (checked 6 source files)
```
- the alembic issue (database.py:6) is due to the same folder name as the module
- the env issue (env.py:9) could be solved by ignoring the whole alembic folder
- but the unused-ignore (database.py:23) is a complete mystery to me, as this is not showing up when running mypy manually.

**It looks like there is some difference between the mypy pre-commit module and when running it manually.**

it could be:
- the version
- not correctly using the `--config-file` arg
